name: task_flow
description: Task Management Application

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  uuid: ^4.0.0
  intl: ^0.19.0

  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - ./lib/images/register/

    - ./lib/images/collection/
    - ./lib/images/collection/priority/

    - ./lib/images/progress/
    - ./lib/images/progress/priority/
    - ./lib/images/progress/backgrounds/
